# Generated by Django 4.2.2 on 2023-07-04 19:22

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", tinymce.models.HTMLField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
